### PR TITLE
Add spm support

### PR DESCRIPTION
**Pull request by popomore**
A nicer package manager: http://spmjs.io
Documentation: http://spmjs.io/documentation

http://spmjs.io/package/mockdate

---

It is a browser-side package manager popular in China, suppling a complete lifecycle managment of package via [spm](https://github.com/spmjs/spm/tree/master).

> If you need ownership of mockdate in spmjs, I can add it for your account after signing in http://spmjs.io.

spmjs/spm#781

### CODE REVIEW

**Comment by popomore** [comment]
add npmignore

before

```
PATH               SIZE       %   
package.json       767 B      0%  
.npmignore         N/A            
README.md          1.67 kB    1%  
LICENSE            1.07 kB    0%  
Gruntfile.js       277 B      0%  
.travis.yml        82 B       0%  
component.json     280 B      0%  
src/mockdate.js    1.7 kB     1%  
tests/chai.js      114.45 kB  47% 
tests/mocha.js     119.98 kB  49% 
tests/tests.js     1.78 kB    1%  
tests/runner.html  338 B      0%  
                                  
DIR                SIZE       %   
src/               1.7 kB     1%  
tests/             236.55 kB  98% 
.                  242.4 kB   100%
```

after

```
PATH             SIZE     %   
package.json     767 B    13% 
.npmignore       19 B     0%  
README.md        1.67 kB  28% 
LICENSE          1.07 kB  18% 
Gruntfile.js     277 B    5%  
.spmignore       19 B     0%  
.travis.yml      82 B     1%  
component.json   280 B    5%  
src/mockdate.js  1.7 kB   29% 
                              
DIR              SIZE     %   
src/             1.7 kB   29% 
.                5.89 kB  100%
```

**Comment by afc163** [comment]
:+1:

**Comment by afc163** [comment]
ping~

**Comment by boblauer** [comment]
@popomore If you wouldn't mind adding me as an owner to this package in spm, I'll be sure to publish all changes to the module there when I make them.

**Comment by popomore** [comment]
Thanks for merging, I have added you as an owner.

**Pull request merged**
