### PR TITLE
Add typescript type definition file

### PR DESCRIPTION
**Pull request by brunoskonrad**
This pull request aims to add typescript types definition to MockDate 😊

### CODE REVIEW

**Comment by brunoskonrad** [comment]
:wave: Up

**Comment by boblauer** [comment]
Thanks for the bump, completely forgot about this. Apologies.

**Comment by brunoskonrad** [comment]
@boblauer yey! No problem, man.
Thanks for accepting it and for creating this library ❤️

**Comment by boblauer** [comment]
Published to npm, `mockdate@2.0.3`

**Pull request merged**
